name: GitHub Actions Demo

on: 
  push:
    inputs:
      branchname:
        description: 'Branch name'
        required: false
        default: 'test1'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
    
      - name: Configure Git
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean

          register:
   runs-on: ubuntu-latest
   name: register
   steps:
     - name: Register build
       id: register-build
       uses: veracode/github-actions-integration-helper@v0.1.6
       with:
         action: registerBuild
         token: ${{ github.event.client_payload.token }}
         appname: ${{ github.event.client_payload.user_config.profile_name }}
         source_repository: ${{ github.event.client_payload.repository.full_name }}
         check_run_id: ${{ github.run_id }}
         check_run_name: ${{ github.workflow }}
         head_sha: ${{ github.event.client_payload.sha }}
         event_type: ${{ github.event.client_payload.event_type }}
         branch: ${{ github.event.client_payload.user_config.sandbox_scan.branch }}
         issue_trigger_flow: ${{ github.event.client_payload.user_config.issue_trigger_flow }}


      
